#!/usr/bin/env php
<?php declare(strict_types=1);
/**
 * @author    Igor Nikolaev <igor.sv.n@gmail.com>
 * @copyright Copyright (c) 2017, Igor Nikolaev
 * @link      http://www.penguin33.ru
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require __DIR__.'/vendor/autoload.php';

use Phestival\Phestival;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();

(new Phestival(!$input->hasParameterOption('--no-debug'), __DIR__))->run($input);
