imports:
    - { resource: parameters.yml }

services:
    _defaults:
        public: false

    command.speak:
        class:  Phestival\Command\SpeakCommand
        public: true
        arguments:
            - speak
            - "@provider_pool"
            - "@speaker"

    http_client:
        class: GuzzleHttp\Client
        arguments:
            -
                connect_timeout: "%http_client_timeout%"
                timeout:         "%http_client_timeout%"

    json_mapper:
        class: JsonMapper
        properties:
            bExceptionOnMissingData:   true
            bIgnoreVisibility:         true
            bStrictObjectTypeChecking: true

    provider_pool:
        class: Phestival\Provider\ProviderPool

    provider.time:
        class: Phestival\Provider\TimeProvider
        arguments:
            - "@translator"

    provider.weather.owm:
        class: Phestival\Provider\Weather\OWM\OWMWeatherProvider
        arguments:
            - "@http_client"
            - "@json_mapper"
            - "%owm_current_weather_uri%"

    speaker:
        class: Phestival\Speaker\Speaker
        arguments:
            - "%language%"

    translator:
        class: Symfony\Component\Translation\Translator
        arguments:
            - "%locale%"
        calls:
            - [addLoader, [yml, "@translator.file_loader"]]

    translator.file_loader:
        class: Symfony\Component\Translation\Loader\YamlFileLoader
