imports:
    - { resource: parameters.yml }

services:
    _defaults:
        public: false

    cache:
        alias: cache.filesystem

    cache.filesystem:
        class: Symfony\Component\Cache\Simple\FilesystemCache
        arguments:
            - ""
            - 0
            - "%cache_dir%"

    command.speak:
        class:  Phestival\Command\SpeakCommand
        public: true
        arguments:
            - speak
            - "@provider_pool"
            - "@speaker"

    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    http_client:
        class: GuzzleHttp\Client
        arguments:
            -
                connect_timeout: "%http_client_timeout%"
                timeout:         "%http_client_timeout%"

    json_mapper:
        class: JsonMapper
        properties:
            bExceptionOnMissingData:   true
            bIgnoreVisibility:         true
            bStrictObjectTypeChecking: true

    number_formatter.feminine:
        parent: number_formatter.masculine
        public: false
        calls:
            - [setTextAttribute, [!php/const:NumberFormatter::DEFAULT_RULESET, "%spellout-cardinal-feminine"]]

    number_formatter.masculine:
        class: NumberFormatter
        arguments:
            - "%locale%"
            - !php/const:NumberFormatter::SPELLOUT

    provider_pool:
        class: Phestival\Provider\ProviderPool

    provider.time:
        class: Phestival\Provider\TimeProvider
        arguments:
            - "@number_formatter.feminine"
            - "@number_formatter.masculine"
            - "@translator"

    provider.weather.owm:
        class: Phestival\Provider\Weather\OWM\OWMWeatherProvider
        arguments:
            - "@http_client"
            - "@json_mapper"
            - "@number_formatter.masculine"
            - "@translator"
            - "%owm_current_weather_uri%"

    speaker:
        class: Phestival\Speaker\Speaker
        arguments:
            - "@filesystem"
            - "%play_command%"
            - "%synthesize_command%"

    translator:
        class: Symfony\Component\Translation\Translator
        arguments:
            - "%locale%"
            - ~
            - "%cache_dir%"
        calls:
            - [addLoader, [yml, "@translator.file_loader"]]

    translator.file_loader:
        class: Symfony\Component\Translation\Loader\YamlFileLoader
