imports:
    - { resource: parameters.yml }

services:
    _defaults:
        public: false

    command.speak:
        class:  Phestival\Command\SpeakCommand
        public: true
        arguments:
            - speak
            - "@provider_pool"
            - "@speaker"

    provider_pool:
        class: Phestival\Provider\ProviderPool

    provider.time:
        class: Phestival\Provider\TimeProvider
        arguments:
            - "@translator"
        tags:
            - { name: provider }

    provider.weather:
        class: Phestival\Provider\Weather\WeatherProvider
        tags:
            - { name: provider }

    speaker:
        class: Phestival\Speaker\Speaker
        arguments:
            - "%language%"

    translator:
        class: Symfony\Component\Translation\Translator
        arguments:
            - "%locale%"
        calls:
            - [addLoader, [yml, "@translator.file_loader"]]

    translator.file_loader:
        class: Symfony\Component\Translation\Loader\YamlFileLoader
