imports:
    - { resource: parameters.yml }

services:
    _defaults:
        public: false

    app:
        class:  Phestival\Console\Application
        public: true
        calls:
            - [ add,               [ "@command.speak" ] ]
            - [ setDefaultCommand, [ speak, true ] ]

    cache:
        alias: cache.filesystem

    cache.filesystem:
        class: Symfony\Component\Cache\Simple\FilesystemCache
        arguments:
            - ""
            - 0
            - "%cache_dir%"

    command.speak:
        class: Phestival\Command\SpeakCommand
        arguments:
            - speak
            - Speaks some useful info
            - "@provider_pool"
            - "@speaker"

    filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    http_client:
        class: GuzzleHttp\Client
        arguments:
            - { connect_timeout: "%http_client_timeout%", timeout: "%http_client_timeout%" }

    json_mapper:
        class: JsonMapper
        properties:
            bExceptionOnMissingData:   true
            bIgnoreVisibility:         true
            bStrictObjectTypeChecking: true

    logger:
        class: Katzgrau\KLogger\Logger
        arguments:
            - "%project_dir%/logs"
            - !php/const:Psr\Log\LogLevel::INFO
            - { filename: log }

    number_formatter.feminine:
        parent: number_formatter.masculine
        public: false
        calls:
            - [ setTextAttribute, [ !php/const:NumberFormatter::DEFAULT_RULESET, "%spellout-cardinal-feminine" ] ]

    number_formatter.masculine:
        class: NumberFormatter
        arguments:
            - "%locale%"
            - !php/const:NumberFormatter::SPELLOUT

    number_formatter.neuter:
        parent: number_formatter.masculine
        public: false
        calls:
            - [ setTextAttribute, [ !php/const:NumberFormatter::DEFAULT_RULESET, "%spellout-cardinal-neuter" ] ]

    provider_pool:
        class: Phestival\Provider\ProviderPool
        arguments:
            - "@logger"

    provider.mail.gmail:
        class: Phestival\Provider\Mail\GmailProvider
        arguments:
            - "@cache"
            - "@http_client"
            - "@number_formatter.neuter"
            - "@translator"
            - "%gmail_feed_uri%"
            - "%gmail_username%"
            - "%gmail_password%"

    provider.time:
        class: Phestival\Provider\TimeProvider
        arguments:
            - "@number_formatter.feminine"
            - "@number_formatter.masculine"
            - "@translator"

    provider.weather.owm:
        class: Phestival\Provider\Weather\OWM\OWMWeatherProvider
        arguments:
            - "@http_client"
            - "@json_mapper"
            - "@logger"
            - "@number_formatter.masculine"
            - "@translator"
            - "%debug%"
            - "%owm_current_weather_uri%"

    speaker:
        class: Phestival\Speaker\Speaker
        arguments:
            - "@filesystem"
            - "%play_command%"
            - "%synthesize_command%"
            - "%cache_dir%"

    translator:
        class: Symfony\Component\Translation\Translator
        arguments:
            - "%locale%"
            - ~
            - "%cache_dir%/translator"
            - "%debug%"
        calls:
            - [ addLoader, [ yml, "@translator.file_loader" ] ]

    translator.file_loader:
        class: Symfony\Component\Translation\Loader\YamlFileLoader
